apiVersion: backstage.io/v1alpha1
kind: Component
spec:
  system: "backstage"
  type:  "website"
  lifecycle: "experimental"
  owner: "analect-io"
metadata:
  name: "test-go-2"
  description: "Testing app launch from Backstage - 2"
  annotations:
    github.com/project-slug: analect-io/test-go-2
    backstage.io/techdocs-ref: dir:.
    argocd/app-name: dev-test-go-2
    backstage.io/kubernetes-id: "test-go-2"
    sonarqube.org/project-key: "test-go-2"
    grafana/tag-selector: "Kubernetes"
    prometheus.io/rule: container_cpu_usage_seconds_total{namespace="test-go-2"}
    prometheus.io/alert: all
  tags:
    - golang
    - "backstage"
    - "website"
    - "experimental"
  links:
    - url: https://test-go-2.
      title: Website
      icon: Website
    - url: https://grafana.analect.com/
      title: Dashboard
      icon: dashboard
    - url: https://alerts.analect.com/
      title: Alerts
      icon: alert
    - url: https://argocd.analect.com/applications/dev-test-go-2?resource=
      title: ArgoCD
      icon: cloud
    - url: https://grafana.analect.com/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=Prometheus&var-namespace=test-go-2&var-resolution=30s
      title: Logs
      icon: cloud
    - url: https://kiali.analect.com/kiali/console/graph/namespaces/?traffic=grpc%2CgrpcRequest%2Chttp%2ChttpRequest%2Ctcp%2CtcpSent&graphType=versionedApp&namespaces=test-go-2&duration=120&refresh=60000&idleNodes=true&layout=kiali-breadthfirst&namespaceLayout=kiali-dagre
      title: Kiali
      icon: cloud
